# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cc0916607f7ddcf1cba2b4d9668ba1cf032bf73e7caf31b577886488d047def111c6ae6518c1fa70bbacd259887162d8ee0d5eaf6c312791c9b419945c7e47c

test:
  secret_key_base: 64a520d8b376fec7492fde93e31323f887d1cbc13eefc6c59b8848500246d619b504fed7e2b2152d89087fee56125178d8b26fe9b96bf582efab297775eb1df4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
